name = "kisskh-proxy"
main = "cfworker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[placement]
mode = "smart"

[ai]
binding = "AI"

[vars]
AUTH_TOKEN = "PJxVzfuySO5IkMGec1pZsFvWDNbiHRE6jULnB2t3"

[[kv_namespaces]]
binding = "ES_CACHE"
id = "77d345738f28442c8a19fadc030eb92e"

[triggers]
crons = ["*/15 * * * *"]
