name = "kisskh-proxy"
main = "cfworker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[placement]
mode = "smart"

[ai]
binding = "AI"

[vars]
AUTH_TOKEN = "nJ0yrMcclqkcYEMTMF5C-jGq9RseMk6FAcJQow"

[[kv_namespaces]]
binding = "ES_CACHE"
id = "644f1a6446574fcf91f6663f124a7b46"

[triggers]
crons = ["*/15 * * * *"]
